### ISSUE TITLE
custom-cards org

### ISSUE THREAD

**Issue by iantrich** [bundito/day-countdown#2]
Invitation to bring your repo over to the community custom-cards organization: https://github.com/custom-cards/information

Let me know if you're interested and I can float you an invitation to the org. Thanks!

**Comment by bundito** [comment]
Hi. Sorry for the delay.

I'm not participating in HomeAssistant usage or development any longer. This add-on is frozen, as is. Feel free to link to it if you wish, but I'm going to add a big note to the README.md about the status.

Thanks for the inclusion.

**Comment by iantrich** [comment]
@bundito moving it to the custom cards org would allow for others to continue upon your work
